import { Injectable, OnModuleInit } from '@nestjs/common';

import { CountriesService } from 'src/core/countries/countries.service';

@Injectable()
export class CountriesSeeder implements OnModuleInit {
  constructor(private readonly countriesService: CountriesService) {}
  async onModuleInit() {
    return true;
  }

  async run() {
    const isModuleInit = await this.onModuleInit();
    if (isModuleInit) {
      const countries = [
        { name: 'Afghanistan' },
        { name: 'Albania' },
        { name: 'Algeria' },
        { name: 'American Samoa' },
        { name: 'Andorra' },
        { name: 'Angola' },
        { name: 'Anguilla' },
        { name: 'Antarctica' },
        { name: 'Antigua and Barbuda' },
        { name: 'Argentina' },
        { name: 'Armenia' },
        { name: 'Aruba' },
        { name: 'Ashmore and Cartier' },
        { name: 'Australia' },
        { name: 'Austria' },
        { name: 'Azerbaijan' },
        { name: 'The Bahamas' },
        { name: 'Bahrain' },
        { name: 'Baker Island' },
        { name: 'Bangladesh' },
        { name: 'Barbados' },
        { name: 'Bassas da India' },
        { name: 'Belarus' },
        { name: 'Belgium' },
        { name: 'Belize' },
        { name: 'Benin' },
        { name: 'Bermuda' },
        { name: 'Bhutan' },
        { name: 'Bolivia' },
        { name: 'Bosnia and Herzegovina' },
        { name: 'Botswana' },
        { name: 'Bouvet Island' },
        { name: 'Brazil' },
        { name: 'British Indian Ocean Territory' },
        { name: 'British Virgin Islands' },
        { name: 'Brunei Darussalam' },
        { name: 'Bulgaria' },
        { name: 'Burkina Faso' },
        { name: 'Burma' },
        { name: 'Burundi' },
        { name: 'Cambodia' },
        { name: 'Cameroon' },
        { name: 'Canada' },
        { name: 'Cape Verde' },
        { name: 'Cayman Islands' },
        { name: 'Central African Republic' },
        { name: 'Chad' },
        { name: 'Chile' },
        { name: 'China' },
        { name: 'Christmas Island' },
        { name: 'Clipperton Island' },
        { name: 'Cocos (Keeling) Islands' },
        { name: 'Colombia' },
        { name: 'Comoros' },
        { name: 'Congo, Democratic Republic of ' },
        { name: 'Congo, Republic of the' },
        { name: 'Cook Islands' },
        { name: 'Coral Sea Islands' },
        { name: 'Costa Rica' },
        { name: "Cote d''Ivoire" },
        { name: 'Croatia' },
        { name: 'Cuba' },
        { name: 'Cyprus' },
        { name: 'Czech Republic' },
        { name: 'Denmark' },
        { name: 'Djibouti' },
        { name: 'Dominica' },
        { name: 'Dominican Republic' },
        { name: 'East Timor' },
        { name: 'Ecuador' },
        { name: 'Egypt' },
        { name: 'El Salvador' },
        { name: 'Equatorial Guinea' },
        { name: 'Eritrea' },
        { name: 'Estonia' },
        { name: 'Ethiopia' },
        { name: 'Europa Island' },
        { name: 'Falkland Islands (Islas Malvin' },
        { name: 'Faroe Islands' },
        { name: 'Fiji' },
        { name: 'Finland' },
        { name: 'France' },
        { name: 'France, Metropolitan' },
        { name: 'French Guiana' },
        { name: 'French Polynesia' },
        { name: 'French Southern and Antarctic ' },
        { name: 'Gabon' },
        { name: 'The Gambia' },
        { name: 'Gaza Strip' },
        { name: 'Georgia' },
        { name: 'Germany' },
        { name: 'Ghana' },
        { name: 'Gibraltar' },
        { name: 'Glorioso Islands' },
        { name: 'Greece' },
        { name: 'Greenland' },
        { name: 'Grenada' },
        { name: 'Guadeloupe' },
        { name: 'Guam' },
        { name: 'Guatemala' },
        { name: 'Guernsey' },
        { name: 'Guinea' },
        { name: 'Guinea-Bissau' },
        { name: 'Guyana' },
        { name: 'Haiti' },
        { name: 'Heard Island and McDonald Isla' },
        { name: 'Holy See (Vatican City)' },
        { name: 'Honduras' },
        { name: 'Hong Kong (SAR)' },
        { name: 'Howland Island' },
        { name: 'Hungary' },
        { name: 'Iceland' },
        { name: 'India' },
        { name: 'Indonesia' },
        { name: 'Iran' },
        { name: 'Iraq' },
        { name: 'Ireland' },
        { name: 'Israel' },
        { name: 'Italy' },
        { name: 'Jamaica' },
        { name: 'Jan Mayen' },
        { name: 'Japan' },
        { name: 'Jarvis Island' },
        { name: 'Jersey' },
        { name: 'Johnston Atoll' },
        { name: 'Jordan' },
        { name: 'Juan de Nova Island' },
        { name: 'Kazakhstan' },
        { name: 'Kenya' },
        { name: 'Kingman Reef' },
        { name: 'Kiribati' },
        { name: 'Korea, North' },
        { name: 'Korea, South' },
        { name: 'Kuwait' },
        { name: 'Kyrgyzstan' },
        { name: 'Laos' },
        { name: 'Latvia' },
        { name: 'Lebanon' },
        { name: 'Lesotho' },
        { name: 'Liberia' },
        { name: 'Libya' },
        { name: 'Liechtenstein' },
        { name: 'Lithuania' },
        { name: 'Luxembourg' },
        { name: 'Macao' },
        { name: 'Macedonia, The Former Yugoslav' },
        { name: 'Madagascar' },
        { name: 'Malawi' },
        { name: 'Malaysia' },
        { name: 'Maldives' },
        { name: 'Mali' },
        { name: 'Malta' },
        { name: 'Man, Isle of' },
        { name: 'Marshall Islands' },
        { name: 'Martinique' },
        { name: 'Mauritania' },
        { name: 'Mauritius' },
        { name: 'Mayotte' },
        { name: 'Mexico' },
        { name: 'Micronesia, Federated States o' },
        { name: 'Midway Islands' },
        { name: 'Miscellaneous (French)' },
        { name: 'Moldova' },
        { name: 'Monaco' },
        { name: 'Mongolia' },
        { name: 'Montenegro' },
        { name: 'Montserrat' },
        { name: 'Morocco' },
        { name: 'Mozambique' },
        { name: 'Myanmar' },
        { name: 'Namibia' },
        { name: 'Nauru' },
        { name: 'Navassa Island' },
        { name: 'Nepal' },
        { name: 'Netherlands' },
        { name: 'Netherlands Antilles' },
        { name: 'New Caledonia' },
        { name: 'New Zealand' },
        { name: 'Nicaragua' },
        { name: 'Niger' },
        { name: 'Nigeria' },
        { name: 'Niue' },
        { name: 'Norfolk Island' },
        { name: 'Northern Mariana Islands' },
        { name: 'Norway' },
        { name: 'Oman' },
        { name: 'Pakistan' },
        { name: 'Palau' },
        { name: 'Palmyra Atoll' },
        { name: 'Panama' },
        { name: 'Papua New Guinea' },
        { name: 'Paracel Islands' },
        { name: 'Paraguay' },
        { name: 'Peru' },
        { name: 'Philippines' },
        { name: 'Pitcairn Islands' },
        { name: 'Poland' },
        { name: 'Portugal' },
        { name: 'Puerto Rico' },
        { name: 'Qatar' },
        { name: 'R?union' },
        { name: 'Romania' },
        { name: 'Russia' },
        { name: 'Rwanda' },
        { name: 'Saint Helena' },
        { name: 'Saint Kitts and Nevis' },
        { name: 'Saint Lucia' },
        { name: 'Saint Pierre and Miquelon' },
        { name: 'Saint Vincent and the Grenadin' },
        { name: 'Samoa' },
        { name: 'San Marino' },
        { name: 'S?o Tom? and Pr?ncipe' },
        { name: 'Saudi Arabia' },
        { name: 'Senegal' },
        { name: 'Serbia' },
        { name: 'Serbia and Montenegro' },
        { name: 'Seychelles' },
        { name: 'Sierra Leone' },
        { name: 'Singapore' },
        { name: 'Slovakia' },
        { name: 'Slovenia' },
        { name: 'Solomon Islands' },
        { name: 'Somalia' },
        { name: 'South Africa' },
        { name: 'South Georgia and the South Sa' },
        { name: 'Spain' },
        { name: 'Spratly Islands' },
        { name: 'Sri Lanka' },
        { name: 'Sudan' },
        { name: 'Suriname' },
        { name: 'Svalbard' },
        { name: 'Swaziland' },
        { name: 'Sweden' },
        { name: 'Switzerland' },
        { name: 'Syria' },
        { name: 'Taiwan' },
        { name: 'Tajikistan' },
        { name: 'Tanzania' },
        { name: 'Thailand' },
        { name: 'Togo' },
        { name: 'Tokelau' },
        { name: 'Tonga' },
        { name: 'Trinidad and Tobago' },
        { name: 'Tromelin Island' },
        { name: 'Tunisia' },
        { name: 'Turkey' },
        { name: 'Turkmenistan' },
        { name: 'Turks and Caicos Islands' },
        { name: 'Tuvalu' },
        { name: 'Uganda' },
        { name: 'Ukraine' },
        { name: 'United Arab Emirates' },
        { name: 'United Kingdom' },
        { name: 'United States' },
        { name: 'United States Minor Outlying I' },
        { name: 'Uruguay' },
        { name: 'Uzbekistan' },
        { name: 'Vanuatu' },
        { name: 'Venezuela' },
        { name: 'Vietnam' },
        { name: 'Virgin Islands' },
        { name: 'Virgin Islands (UK)' },
        { name: 'Virgin Islands (US)' },
        { name: 'Wake Island' },
        { name: 'Wallis and Futuna' },
        { name: 'West Bank' },
        { name: 'Western Sahara' },
        { name: 'Western Samoa' },
        { name: 'World' },
        { name: 'Yemen' },
        { name: 'Yugoslavia' },
        { name: 'Zaire' },
        { name: 'Zambia' },
        { name: 'Zimbabwe' },
        { name: 'Palestinian Territory, Occupie' },
      ];
      await this.countriesService.bulkCreate(countries);
    }
  }
}
