AWSTemplateFormatVersion: '2010-09-09'
Description: backend container on ecs cluster

Parameters:

  ImageTag:
    Type: "String"
    Description: "Image tag to deploy from mp-marketplace-backend repository"

  SystemManagerEmails:
    Type: "String"
    Description: "Predefined system manager emails"

Resources:

  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: marketplace
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRole
      ContainerDefinitions:
        - Name: mp-marketplace-backend
          Image: !Sub
            - 655619865059.dkr.ecr.eu-central-1.amazonaws.com/marketplace-backend:${Tag}
            - { Tag: !Ref 'ImageTag' }
          Cpu: 256
          Memory: 512
          Environment:
            - Name: PORT
              Value: 8080
            - Name: GRAPHQL_PLAYGROUND_ENABLED
              Value: true
            - Name: POSTGRES_HOST
              Value: !ImportValue 'BackendDatabaseAddress'
            - Name: POSTGRES_USERNAME
              Value: !ImportValue 'BackendDatabaseUser'
            - Name: POSTGRES_PASSWORD
              Value: !ImportValue 'BackendDatabasePassword'
            - Name: POSTGRES_DATABASE
              Value: !ImportValue 'BackendDatabaseName'
            - Name: SYSTEM_MANAGER_EMAILS
              Value: !Ref 'SystemManagerEmails'
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 'mp-marketplace-backend-dev'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'mp-marketplace-backend-dev'

  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      ServiceName: mp-marketplace-backend
      TaskDefinition: !Ref Task
      Cluster: !ImportValue 'ECSCluster'
      LaunchType: FARGATE
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue PublicSubnet1
            - !ImportValue PublicSubnet2
          SecurityGroups:
            - !ImportValue ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: mp-marketplace-backend
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: mp-marketplace-backend
      VpcId: !ImportValue VPC
      Port: 8080
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 10
      TargetType: ip
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '60'

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue Listener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - /graphql
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

Outputs:

  GraphqlEndpoint:
    Description: Graphql API Endpoint
    Value: !Join ['', ['http://', !ImportValue DomainName, '/graphql']]
    Export:
      Name: 'BackendGraphqlEndpoint'
