version: '3.5'

services:
  postgres:
    image: 'postgres:13.3-alpine'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mp_password
      - POSTGRES_USER=mp_user
      - POSTGRES_DB=mp
    volumes:
      - 'postgres:/var/lib/postgresql/data:Z'
volumes:
  postgres:
